use crate::features::{get_feature_names, ExtractedFeatures};
use serde::{Deserialize, Serialize};

/// Embedded default model weights generated by offline Python training.
const DEFAULT_MODEL_JSON: &str = include_str!("../../../ml-models/file_type_classifier_trees.json");

/// Individual Decision Tree Node definition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecisionTreeNode {
    pub node_count: usize,
    pub children_left: Vec<i32>,
    pub children_right: Vec<i32>,
    pub feature: Vec<i32>,
    pub threshold: Vec<f32>,
    pub value: Vec<f32>,
}

impl DecisionTreeNode {
    /// Evaluates a single decision tree against the input feature vector.
    pub fn predict_scalar(&self, features: &[f32]) -> f32 {
        let mut node = 0usize;
        loop {
            let left = self.children_left[node];
            let right = self.children_right[node];

            if left == -1 && right == -1 {
                // Leaf node
                return self.value[node];
            }

            let feat_idx = self.feature[node] as usize;
            let thresh = self.threshold[node];

            let feat_val = if feat_idx < features.len() {
                features[feat_idx]
            } else {
                0.0
            };

            if feat_val <= thresh {
                node = left as usize;
            } else {
                node = right as usize;
            }
        }
    }
}

/// Native Gradient Boosted Decision Tree Ensemble representation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TreeEnsembleModel {
    pub n_classes: usize,
    pub n_estimators: usize,
    pub n_features: usize,
    pub class_names: Vec<String>,
    pub feature_names: Vec<String>,
    pub feature_importances: Vec<f32>,
    pub init_prior: Vec<f32>,
    pub trees: Vec<Vec<DecisionTreeNode>>,
}

/// Explainable feature contribution descriptor (§33, §31).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeatureContribution {
    pub feature_index: usize,
    pub feature_name: String,
    pub value: f32,
    pub global_importance: f32,
}

/// Standalone Classification Result.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ClassificationResult {
    /// Top predicted file type (e.g. "jpeg", "png", "pdf", "zip", "sqlite", "unknown").
    pub predicted_class: String,
    /// Confidence probability (0.0–1.0) for the predicted class.
    pub probability: f32,
    /// Probability distribution across all evaluated classes.
    pub class_probabilities: Vec<(String, f32)>,
    /// Top-5 most informative features explaining this classification (§33).
    pub top_features: Vec<FeatureContribution>,
}

/// File-Type Classifier Engine (§33).
pub struct FileTypeClassifier {
    model: TreeEnsembleModel,
}

impl Default for FileTypeClassifier {
    fn default() -> Self {
        Self::load_default().expect("Failed to load default embedded file-type classifier model")
    }
}

impl FileTypeClassifier {
    /// Loads default embedded model weights.
    pub fn load_default() -> Result<Self, serde_json::Error> {
        let model: TreeEnsembleModel = serde_json::from_str(DEFAULT_MODEL_JSON)?;
        Ok(Self { model })
    }

    /// Loads model weights from a JSON string.
    pub fn from_json_str(json_str: &str) -> Result<Self, serde_json::Error> {
        let model: TreeEnsembleModel = serde_json::from_str(json_str)?;
        Ok(Self { model })
    }

    /// Predicts raw log-odds across all classes for an extracted feature vector.
    pub fn predict_raw(&self, features: &ExtractedFeatures) -> Vec<f32> {
        let mut raw_scores = vec![0.0f32; self.model.n_classes];

        // Init prior log-odds if present
        for (i, &p) in self.model.init_prior.iter().enumerate() {
            if i < raw_scores.len() {
                raw_scores[i] = if p > 0.0 { p.ln() } else { 0.0 };
            }
        }

        // Sum tree ensemble predictions
        for class_trees in &self.model.trees {
            for (class_idx, tree) in class_trees.iter().enumerate() {
                if class_idx < raw_scores.len() {
                    raw_scores[class_idx] += tree.predict_scalar(&features.vector);
                }
            }
        }

        raw_scores
    }

    /// Predicts softmax class probabilities for candidate features.
    pub fn predict_proba(&self, features: &ExtractedFeatures) -> Vec<(String, f32)> {
        let raw = self.predict_raw(features);

        // Softmax with numerical stability
        let max_val = raw.iter().copied().fold(f32::NEG_INFINITY, f32::max);
        let mut exp_scores = Vec::with_capacity(raw.len());
        let mut sum_exp = 0.0f32;

        for &val in &raw {
            let e = (val - max_val).exp();
            exp_scores.push(e);
            sum_exp += e;
        }

        let mut results = Vec::with_capacity(self.model.n_classes);
        for (idx, &e) in exp_scores.iter().enumerate() {
            let prob = if sum_exp > 0.0 { e / sum_exp } else { 0.0 };
            let class_name = self
                .model
                .class_names
                .get(idx)
                .cloned()
                .unwrap_or_else(|| format!("class_{}", idx));
            results.push((class_name, prob));
        }

        results
    }

    /// Classifies candidate features and extracts explainable basis (§33).
    pub fn classify(&self, features: &ExtractedFeatures) -> ClassificationResult {
        let probabilities = self.predict_proba(features);

        let mut best_class = "unknown".to_string();
        let mut best_prob = 0.0f32;

        for (name, prob) in &probabilities {
            if *prob > best_prob {
                best_prob = *prob;
                best_class = name.clone();
            }
        }

        // Extract top-5 contributing features based on model feature importances
        let feat_names = get_feature_names();
        let mut ranked_features: Vec<(usize, f32)> = self
            .model
            .feature_importances
            .iter()
            .copied()
            .enumerate()
            .collect();
        ranked_features.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

        let top_features = ranked_features
            .into_iter()
            .take(5)
            .map(|(idx, imp)| {
                let name = feat_names.get(idx).cloned().unwrap_or_else(|| format!("feat_{}", idx));
                let value = features.vector.get(idx).copied().unwrap_or(0.0);
                FeatureContribution {
                    feature_index: idx,
                    feature_name: name,
                    value,
                    global_importance: imp,
                }
            })
            .collect();

        ClassificationResult {
            predicted_class: best_class,
            probability: best_prob,
            class_probabilities: probabilities,
            top_features,
        }
    }
}
